### ISSUE TITLE
Could the setup of dependencies be reduced to a one-liner and be automated?

### ISSUE THREAD

**Issue by mmtmn** [GregDavidson/wicci-core-S0_lib#1]
I find the most challenging part of this repository to be the setup.

If the setup could be an automated, one liner, that would be very helpful. Also, "difficulty-scaled tutorials", or tutorials from easiest to hardest, would greatly help with the adoption of more contributors in my humble opinion...

**Comment by mmtmn** [comment]
I've seen the makefile, but I'm talking about this:

"Other projects may only need a subset of these materials. The higher-numbered Schemas depend on the lower-numbered Schemas, so if, e.g., you want the functionality of S4_doc, you will need Core (which contains C_lib and S0_lib), S1_refs, S2_core and S3_more."

**Comment by mmtmn** [comment]
Maybe a dependency resolving algorithm would do the trick? I'm not sure, let me know if that works, if that would even be   something that is possible in future implementations, cheers!

**Comment by GregDavidson** [comment]
At the moment we're slowed down by (1) making our install scripts more clear, flexible and portable [largely done now!] and then (2) we need to squash a software rot bug caused by some changes in how C extensions talk to PostgreSQL internals.    Shortly we will be having a group going through the whole codebase and probably making it nicer in many ways.  A radical idea is to refactor the 8 schemas into a larger number of PostgreSQL Loadable Extensions.  Alejandrosame is looking at the possibility of using Nix derivations to manage the dependencies among such Extensions.  The current arrangement of having only 8 Schemas, where Schema N is only dependent on Schemas 0..N-1 is probably simpler though!  I hope that a lot of this gets sorted in the next pass through the Wicci!

**Comment by mmtmn** [comment]
I had to deal with a memory leak and end of the year crunch with
university. Sorry I haven't been able to help out much lately everyone.
